/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppVideosIndexRouteImport } from './routes/app/videos/index'
import { Route as AppBatchesIndexRouteImport } from './routes/app/batches/index'
import { Route as AppVideosVideoIdRouteImport } from './routes/app/videos/$videoId'
import { Route as AppBatchesBatchIdRouteImport } from './routes/app/batches/$batchId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosIndexRoute = AppVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIndexRoute = AppBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosVideoIdRoute = AppVideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesBatchIdRoute = AppBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/batches/$batchId': typeof AppBatchesBatchIdRoute
  '/app/videos/$videoId': typeof AppVideosVideoIdRoute
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/videos/': typeof AppVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/batches/$batchId': typeof AppBatchesBatchIdRoute
  '/app/videos/$videoId': typeof AppVideosVideoIdRoute
  '/app/batches': typeof AppBatchesIndexRoute
  '/app/videos': typeof AppVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/batches/$batchId': typeof AppBatchesBatchIdRoute
  '/app/videos/$videoId': typeof AppVideosVideoIdRoute
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/videos/': typeof AppVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/'
    | '/app/batches/$batchId'
    | '/app/videos/$videoId'
    | '/app/batches/'
    | '/app/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/settings'
    | '/app'
    | '/app/batches/$batchId'
    | '/app/videos/$videoId'
    | '/app/batches'
    | '/app/videos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/'
    | '/app/batches/$batchId'
    | '/app/videos/$videoId'
    | '/app/batches/'
    | '/app/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/videos/': {
      id: '/app/videos/'
      path: '/videos'
      fullPath: '/app/videos/'
      preLoaderRoute: typeof AppVideosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/': {
      id: '/app/batches/'
      path: '/batches'
      fullPath: '/app/batches/'
      preLoaderRoute: typeof AppBatchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/videos/$videoId': {
      id: '/app/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/app/videos/$videoId'
      preLoaderRoute: typeof AppVideosVideoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/$batchId': {
      id: '/app/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/app/batches/$batchId'
      preLoaderRoute: typeof AppBatchesBatchIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBatchesBatchIdRoute: typeof AppBatchesBatchIdRoute
  AppVideosVideoIdRoute: typeof AppVideosVideoIdRoute
  AppBatchesIndexRoute: typeof AppBatchesIndexRoute
  AppVideosIndexRoute: typeof AppVideosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBatchesBatchIdRoute: AppBatchesBatchIdRoute,
  AppVideosVideoIdRoute: AppVideosVideoIdRoute,
  AppBatchesIndexRoute: AppBatchesIndexRoute,
  AppVideosIndexRoute: AppVideosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
