"""add_default_column_mapping_to_app_settings

Revision ID: 07cfd31b6aab
Revises: 0bc455c01bbc
Create Date: 2026-03-14 00:54:52.365285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07cfd31b6aab'
down_revision: Union[str, Sequence[str], None] = '0bc455c01bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('default_script_column', sa.String(length=100), server_default='script_text', nullable=False))
    op.add_column('app_settings', sa.Column('default_voice_column', sa.String(length=100), server_default='voice_id', nullable=False))
    op.add_column('app_settings', sa.Column('default_style_column', sa.String(length=100), server_default='style', nullable=False))
    op.add_column('app_settings', sa.Column('default_top_text_column', sa.String(length=100), server_default='top_text', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'default_top_text_column')
    op.drop_column('app_settings', 'default_style_column')
    op.drop_column('app_settings', 'default_voice_column')
    op.drop_column('app_settings', 'default_script_column')
    # ### end Alembic commands ###
