"""remove batch status add video prompt use enums

Revision ID: 0bc455c01bbc
Revises: 3fd44d749626
Create Date: 2026-03-14 00:31:12.136984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '0bc455c01bbc'
down_revision: Union[str, Sequence[str], None] = '3fd44d749626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'status')
    op.add_column('videos', sa.Column('prompt', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'prompt')
    op.add_column('batches', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
