"""add file_name to videos and column_defaults to app_settings

Revision ID: 239f9a65d33f
Revises: a8f2e1c3d4b5
Create Date: 2026-03-19 17:47:59.851100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '239f9a65d33f'
down_revision: Union[str, Sequence[str], None] = 'a8f2e1c3d4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('column_defaults', postgresql.JSON(astext_type=sa.Text()), server_default='{"script_text": "script_text", "voice_id": "voice_id", "style": "style", "top_text": "top_text", "file_name": "file_name"}', nullable=False))
    op.drop_column('app_settings', 'default_style_column')
    op.drop_column('app_settings', 'default_top_text_column')
    op.drop_column('app_settings', 'default_script_column')
    op.drop_column('app_settings', 'default_voice_column')
    op.add_column('videos', sa.Column('file_name', sa.String(length=500), nullable=True))
    op.alter_column('videos', 'voice_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'voice_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('videos', 'file_name')
    op.add_column('app_settings', sa.Column('default_voice_column', sa.VARCHAR(length=100), server_default=sa.text("'voice_id'::character varying"), autoincrement=False, nullable=False))
    op.add_column('app_settings', sa.Column('default_script_column', sa.VARCHAR(length=100), server_default=sa.text("'script_text'::character varying"), autoincrement=False, nullable=False))
    op.add_column('app_settings', sa.Column('default_top_text_column', sa.VARCHAR(length=100), server_default=sa.text("'top_text'::character varying"), autoincrement=False, nullable=False))
    op.add_column('app_settings', sa.Column('default_style_column', sa.VARCHAR(length=100), server_default=sa.text("'style'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('app_settings', 'column_defaults')
    # ### end Alembic commands ###
