"""add_index_on_current_stage

Revision ID: 29dc417ed63d
Revises: c8f1f9bae6d2
Create Date: 2026-03-16 17:58:29.214242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '29dc417ed63d'
down_revision: Union[str, Sequence[str], None] = 'c8f1f9bae6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_videos_current_stage'), 'videos', ['current_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_current_stage'), table_name='videos')
    # ### end Alembic commands ###
