"""remove_width_height_from_videos

Revision ID: 3dd36cf742e2
Revises: 820cb640e62e
Create Date: 2026-03-17 16:35:35.319752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd36cf742e2'
down_revision: Union[str, Sequence[str], None] = '820cb640e62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'width')
    op.drop_column('videos', 'height')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('height', sa.INTEGER(), server_default=sa.text('1920'), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('width', sa.INTEGER(), server_default=sa.text('1080'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
