"""add batches table and statistics fields

Revision ID: 3fd44d749626
Revises: a1b2c3d4e5f6
Create Date: 2026-03-13 19:29:50.489253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3fd44d749626'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_videos', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('avg_cost_per_video_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shots', sa.Column('tokens_used', sa.Integer(), nullable=False))
    op.add_column('shots', sa.Column('generation_time_ms', sa.Integer(), nullable=False))
    op.add_column('shots', sa.Column('cost_usd', sa.Float(), nullable=False))
    op.add_column('videos', sa.Column('top_text', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('tokens_used', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('generation_time_ms', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('total_cost_usd', sa.Float(), nullable=False))
    op.add_column('videos', sa.Column('avg_cost_per_shot_usd', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'videos', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'avg_cost_per_shot_usd')
    op.drop_column('videos', 'total_cost_usd')
    op.drop_column('videos', 'generation_time_ms')
    op.drop_column('videos', 'tokens_used')
    op.drop_column('videos', 'top_text')
    op.drop_column('shots', 'cost_usd')
    op.drop_column('shots', 'generation_time_ms')
    op.drop_column('shots', 'tokens_used')
    op.drop_table('batches')
    # ### end Alembic commands ###
