"""remove prompt from videos, tokens_used and generation_time_ms from shots

Revision ID: 485b2055cb24
Revises: ca7e952f3c09
Create Date: 2026-03-16 00:51:26.723725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485b2055cb24'
down_revision: Union[str, Sequence[str], None] = 'ca7e952f3c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shots', 'tokens_used')
    op.drop_column('shots', 'generation_time_ms')
    op.drop_column('videos', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('prompt', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.add_column('shots', sa.Column('generation_time_ms', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shots', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
