"""add_status_to_batches

Revision ID: 6681ae86ec51
Revises: 3fbe751468b2
Create Date: 2026-03-16 16:15:55.809824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '6681ae86ec51'
down_revision: Union[str, Sequence[str], None] = '3fbe751468b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('status', sa.String(length=30), nullable=False, server_default='processing'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'status')
    # ### end Alembic commands ###
