"""add duration_ms to videos

Revision ID: 805b44dd1bb0
Revises: 485b2055cb24
Create Date: 2026-03-16 09:52:10.800366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '805b44dd1bb0'
down_revision: Union[str, Sequence[str], None] = '485b2055cb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('duration_ms', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'duration_ms')
    # ### end Alembic commands ###
