"""add_audio_url_to_videos

Revision ID: 820cb640e62e
Revises: 159381856cbc
Create Date: 2026-03-17 16:29:01.767999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820cb640e62e'
down_revision: Union[str, Sequence[str], None] = '159381856cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('audio_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'audio_url')
    # ### end Alembic commands ###
