"""add_prompt_to_videos

Revision ID: c8f1f9bae6d2
Revises: d688fb97c3bf
Create Date: 2026-03-16 16:51:09.322341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f1f9bae6d2'
down_revision: Union[str, Sequence[str], None] = 'd688fb97c3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'prompt')
    # ### end Alembic commands ###
