"""split domains batches shots videos

Revision ID: e9e1bdbfcdd2
Revises: f69cb60224da
Create Date: 2026-03-14 12:03:39.454988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e9e1bdbfcdd2'
down_revision: Union[str, Sequence[str], None] = 'f69cb60224da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
