"""add upload fields and error_message to batches

Revision ID: f69cb60224da
Revises: b2c3d4e5f6a7
Create Date: 2026-03-14 02:49:18.864723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f69cb60224da'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('column_mapping', sa.JSON(), nullable=True))
    op.add_column('batches', sa.Column('file_name', sa.String(length=500), nullable=True))
    op.add_column('batches', sa.Column('file_key', sa.String(length=500), nullable=True))
    op.add_column('batches', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'error_message')
    op.drop_column('batches', 'file_key')
    op.drop_column('batches', 'file_name')
    op.drop_column('batches', 'column_mapping')
    # ### end Alembic commands ###
