/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppSettingsRead,
  AppSettingsUpdate,
  AuthStatus,
  BatchSummary,
  HTTPValidationError,
  HealthCheckHealthGet200,
  ListVideosApiV1VideosGetParams,
  LoginRequest,
  PageResponseVideoRead,
  RootGet200,
  ShotCreate,
  ShotRead,
  ShotUpdate,
  VideoCreate,
  VideoRead,
  VideoReadWithShots,
  VideoUpdate
} from './model';

import { customInstance } from './custom-instance';
import type { ErrorType , BodyType } from './custom-instance';
type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Root endpoint.
 * @summary Root
 */
export const rootGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RootGet200>(
      {url: `/`, method: 'GET', signal
    },
      options);
    }
  



export const getRootGetQueryKey = () => {
    return [
    `/`
    ] as const;
    }

    
export const getRootGetQueryOptions = <TData = Awaited<ReturnType<typeof rootGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRootGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({ signal }) => rootGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type RootGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootGet>>>
export type RootGetQueryError = ErrorType<unknown>


export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Root
 */

export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getRootGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Health check endpoint.
 * @summary Health Check
 */
export const healthCheckHealthGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<HealthCheckHealthGet200>(
      {url: `/health`, method: 'GET', signal
    },
      options);
    }
  



export const getHealthCheckHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getHealthCheckHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckHealthGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheckHealthGet>>> = ({ signal }) => healthCheckHealthGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type HealthCheckHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheckHealthGet>>>
export type HealthCheckHealthGetQueryError = ErrorType<unknown>


export function useHealthCheckHealthGet<TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheckHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthCheckHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useHealthCheckHealthGet<TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheckHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthCheckHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useHealthCheckHealthGet<TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Health Check
 */

export function useHealthCheckHealthGet<TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getHealthCheckHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Verify password and set signed session cookie.
 * @summary Login
 */
export const loginApiV1AuthLoginPost = (
    loginRequest: BodyType<LoginRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthStatus>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getLoginApiV1AuthLoginPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>, TError,{data: BodyType<LoginRequest>}, TContext> => {

const mutationKey = ['loginApiV1AuthLoginPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>, {data: BodyType<LoginRequest>}> = (props) => {
          const {data} = props ?? {};

          return  loginApiV1AuthLoginPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginApiV1AuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>>
    export type LoginApiV1AuthLoginPostMutationBody = BodyType<LoginRequest>
    export type LoginApiV1AuthLoginPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Login
 */
export const useLoginApiV1AuthLoginPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>,
        TError,
        {data: BodyType<LoginRequest>},
        TContext
      > => {

      const mutationOptions = getLoginApiV1AuthLoginPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Clear session cookie.
 * @summary Logout
 */
export const logoutApiV1AuthLogoutPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthStatus>(
      {url: `/api/v1/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getLogoutApiV1AuthLogoutPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>, TError,void, TContext> => {

const mutationKey = ['logoutApiV1AuthLogoutPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>, void> = () => {
          

          return  logoutApiV1AuthLogoutPost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutApiV1AuthLogoutPostMutationResult = NonNullable<Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>>
    
    export type LogoutApiV1AuthLogoutPostMutationError = ErrorType<unknown>

    /**
 * @summary Logout
 */
export const useLogoutApiV1AuthLogoutPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutApiV1AuthLogoutPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Check if current session is valid.
 * @summary Me
 */
export const meApiV1AuthMeGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthStatus>(
      {url: `/api/v1/auth/me`, method: 'GET', signal
    },
      options);
    }
  



export const getMeApiV1AuthMeGetQueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }

    
export const getMeApiV1AuthMeGetQueryOptions = <TData = Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeApiV1AuthMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof meApiV1AuthMeGet>>> = ({ signal }) => meApiV1AuthMeGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type MeApiV1AuthMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof meApiV1AuthMeGet>>>
export type MeApiV1AuthMeGetQueryError = ErrorType<HTTPValidationError>


export function useMeApiV1AuthMeGet<TData = Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meApiV1AuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof meApiV1AuthMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useMeApiV1AuthMeGet<TData = Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meApiV1AuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof meApiV1AuthMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useMeApiV1AuthMeGet<TData = Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Me
 */

export function useMeApiV1AuthMeGet<TData = Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meApiV1AuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getMeApiV1AuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Create a new video record.
 * @summary Create Video
 */
export const createVideoApiV1VideosPost = (
    videoCreate: BodyType<VideoCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<VideoRead>(
      {url: `/api/v1/videos/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: videoCreate, signal
    },
      options);
    }
  


export const getCreateVideoApiV1VideosPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVideoApiV1VideosPost>>, TError,{data: BodyType<VideoCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createVideoApiV1VideosPost>>, TError,{data: BodyType<VideoCreate>}, TContext> => {

const mutationKey = ['createVideoApiV1VideosPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVideoApiV1VideosPost>>, {data: BodyType<VideoCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createVideoApiV1VideosPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateVideoApiV1VideosPostMutationResult = NonNullable<Awaited<ReturnType<typeof createVideoApiV1VideosPost>>>
    export type CreateVideoApiV1VideosPostMutationBody = BodyType<VideoCreate>
    export type CreateVideoApiV1VideosPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Video
 */
export const useCreateVideoApiV1VideosPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVideoApiV1VideosPost>>, TError,{data: BodyType<VideoCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createVideoApiV1VideosPost>>,
        TError,
        {data: BodyType<VideoCreate>},
        TContext
      > => {

      const mutationOptions = getCreateVideoApiV1VideosPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * List videos with optional batch_id filter.
 * @summary List Videos
 */
export const listVideosApiV1VideosGet = (
    params?: ListVideosApiV1VideosGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponseVideoRead>(
      {url: `/api/v1/videos/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListVideosApiV1VideosGetQueryKey = (params?: ListVideosApiV1VideosGetParams,) => {
    return [
    `/api/v1/videos/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListVideosApiV1VideosGetQueryOptions = <TData = Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError = ErrorType<HTTPValidationError>>(params?: ListVideosApiV1VideosGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVideosApiV1VideosGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVideosApiV1VideosGet>>> = ({ signal }) => listVideosApiV1VideosGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListVideosApiV1VideosGetQueryResult = NonNullable<Awaited<ReturnType<typeof listVideosApiV1VideosGet>>>
export type ListVideosApiV1VideosGetQueryError = ErrorType<HTTPValidationError>


export function useListVideosApiV1VideosGet<TData = Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListVideosApiV1VideosGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVideosApiV1VideosGet>>,
          TError,
          Awaited<ReturnType<typeof listVideosApiV1VideosGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListVideosApiV1VideosGet<TData = Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListVideosApiV1VideosGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVideosApiV1VideosGet>>,
          TError,
          Awaited<ReturnType<typeof listVideosApiV1VideosGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListVideosApiV1VideosGet<TData = Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListVideosApiV1VideosGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Videos
 */

export function useListVideosApiV1VideosGet<TData = Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListVideosApiV1VideosGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVideosApiV1VideosGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListVideosApiV1VideosGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * List batch summaries with aggregate stats.
 * @summary List Batches
 */
export const listBatchesApiV1VideosBatchesGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BatchSummary[]>(
      {url: `/api/v1/videos/batches`, method: 'GET', signal
    },
      options);
    }
  



export const getListBatchesApiV1VideosBatchesGetQueryKey = () => {
    return [
    `/api/v1/videos/batches`
    ] as const;
    }

    
export const getListBatchesApiV1VideosBatchesGetQueryOptions = <TData = Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBatchesApiV1VideosBatchesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>> = ({ signal }) => listBatchesApiV1VideosBatchesGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListBatchesApiV1VideosBatchesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>>
export type ListBatchesApiV1VideosBatchesGetQueryError = ErrorType<HTTPValidationError>


export function useListBatchesApiV1VideosBatchesGet<TData = Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>,
          TError,
          Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListBatchesApiV1VideosBatchesGet<TData = Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>,
          TError,
          Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListBatchesApiV1VideosBatchesGet<TData = Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Batches
 */

export function useListBatchesApiV1VideosBatchesGet<TData = Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBatchesApiV1VideosBatchesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListBatchesApiV1VideosBatchesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Get a video by ID, including its shots.
 * @summary Get Video
 */
export const getVideoApiV1VideosVideoIdGet = (
    videoId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<VideoReadWithShots>(
      {url: `/api/v1/videos/${videoId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetVideoApiV1VideosVideoIdGetQueryKey = (videoId?: string,) => {
    return [
    `/api/v1/videos/${videoId}`
    ] as const;
    }

    
export const getGetVideoApiV1VideosVideoIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError = ErrorType<HTTPValidationError>>(videoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVideoApiV1VideosVideoIdGetQueryKey(videoId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>> = ({ signal }) => getVideoApiV1VideosVideoIdGet(videoId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(videoId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVideoApiV1VideosVideoIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>>
export type GetVideoApiV1VideosVideoIdGetQueryError = ErrorType<HTTPValidationError>


export function useGetVideoApiV1VideosVideoIdGet<TData = Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>,
          TError,
          Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVideoApiV1VideosVideoIdGet<TData = Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>,
          TError,
          Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVideoApiV1VideosVideoIdGet<TData = Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Video
 */

export function useGetVideoApiV1VideosVideoIdGet<TData = Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoApiV1VideosVideoIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetVideoApiV1VideosVideoIdGetQueryOptions(videoId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Update a video.
 * @summary Update Video
 */
export const updateVideoApiV1VideosVideoIdPatch = (
    videoId: string,
    videoUpdate: BodyType<VideoUpdate>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<VideoRead>(
      {url: `/api/v1/videos/${videoId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: videoUpdate
    },
      options);
    }
  


export const getUpdateVideoApiV1VideosVideoIdPatchMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVideoApiV1VideosVideoIdPatch>>, TError,{videoId: string;data: BodyType<VideoUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateVideoApiV1VideosVideoIdPatch>>, TError,{videoId: string;data: BodyType<VideoUpdate>}, TContext> => {

const mutationKey = ['updateVideoApiV1VideosVideoIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateVideoApiV1VideosVideoIdPatch>>, {videoId: string;data: BodyType<VideoUpdate>}> = (props) => {
          const {videoId,data} = props ?? {};

          return  updateVideoApiV1VideosVideoIdPatch(videoId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateVideoApiV1VideosVideoIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateVideoApiV1VideosVideoIdPatch>>>
    export type UpdateVideoApiV1VideosVideoIdPatchMutationBody = BodyType<VideoUpdate>
    export type UpdateVideoApiV1VideosVideoIdPatchMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Video
 */
export const useUpdateVideoApiV1VideosVideoIdPatch = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVideoApiV1VideosVideoIdPatch>>, TError,{videoId: string;data: BodyType<VideoUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateVideoApiV1VideosVideoIdPatch>>,
        TError,
        {videoId: string;data: BodyType<VideoUpdate>},
        TContext
      > => {

      const mutationOptions = getUpdateVideoApiV1VideosVideoIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Delete a video and its shots.
 * @summary Delete Video
 */
export const deleteVideoApiV1VideosVideoIdDelete = (
    videoId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/videos/${videoId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteVideoApiV1VideosVideoIdDeleteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVideoApiV1VideosVideoIdDelete>>, TError,{videoId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteVideoApiV1VideosVideoIdDelete>>, TError,{videoId: string}, TContext> => {

const mutationKey = ['deleteVideoApiV1VideosVideoIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVideoApiV1VideosVideoIdDelete>>, {videoId: string}> = (props) => {
          const {videoId} = props ?? {};

          return  deleteVideoApiV1VideosVideoIdDelete(videoId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteVideoApiV1VideosVideoIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVideoApiV1VideosVideoIdDelete>>>
    
    export type DeleteVideoApiV1VideosVideoIdDeleteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Video
 */
export const useDeleteVideoApiV1VideosVideoIdDelete = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVideoApiV1VideosVideoIdDelete>>, TError,{videoId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVideoApiV1VideosVideoIdDelete>>,
        TError,
        {videoId: string},
        TContext
      > => {

      const mutationOptions = getDeleteVideoApiV1VideosVideoIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Create a shot for a video.
 * @summary Create Shot
 */
export const createShotApiV1VideosVideoIdShotsPost = (
    videoId: string,
    shotCreate: BodyType<ShotCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ShotRead>(
      {url: `/api/v1/videos/${videoId}/shots/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: shotCreate, signal
    },
      options);
    }
  


export const getCreateShotApiV1VideosVideoIdShotsPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShotApiV1VideosVideoIdShotsPost>>, TError,{videoId: string;data: BodyType<ShotCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createShotApiV1VideosVideoIdShotsPost>>, TError,{videoId: string;data: BodyType<ShotCreate>}, TContext> => {

const mutationKey = ['createShotApiV1VideosVideoIdShotsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createShotApiV1VideosVideoIdShotsPost>>, {videoId: string;data: BodyType<ShotCreate>}> = (props) => {
          const {videoId,data} = props ?? {};

          return  createShotApiV1VideosVideoIdShotsPost(videoId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateShotApiV1VideosVideoIdShotsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createShotApiV1VideosVideoIdShotsPost>>>
    export type CreateShotApiV1VideosVideoIdShotsPostMutationBody = BodyType<ShotCreate>
    export type CreateShotApiV1VideosVideoIdShotsPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Shot
 */
export const useCreateShotApiV1VideosVideoIdShotsPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShotApiV1VideosVideoIdShotsPost>>, TError,{videoId: string;data: BodyType<ShotCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createShotApiV1VideosVideoIdShotsPost>>,
        TError,
        {videoId: string;data: BodyType<ShotCreate>},
        TContext
      > => {

      const mutationOptions = getCreateShotApiV1VideosVideoIdShotsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * List all shots for a video, ordered by sequence.
 * @summary List Shots
 */
export const listShotsApiV1VideosVideoIdShotsGet = (
    videoId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ShotRead[]>(
      {url: `/api/v1/videos/${videoId}/shots/`, method: 'GET', signal
    },
      options);
    }
  



export const getListShotsApiV1VideosVideoIdShotsGetQueryKey = (videoId?: string,) => {
    return [
    `/api/v1/videos/${videoId}/shots/`
    ] as const;
    }

    
export const getListShotsApiV1VideosVideoIdShotsGetQueryOptions = <TData = Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError = ErrorType<HTTPValidationError>>(videoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListShotsApiV1VideosVideoIdShotsGetQueryKey(videoId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>> = ({ signal }) => listShotsApiV1VideosVideoIdShotsGet(videoId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(videoId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListShotsApiV1VideosVideoIdShotsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>>
export type ListShotsApiV1VideosVideoIdShotsGetQueryError = ErrorType<HTTPValidationError>


export function useListShotsApiV1VideosVideoIdShotsGet<TData = Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>,
          TError,
          Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListShotsApiV1VideosVideoIdShotsGet<TData = Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>,
          TError,
          Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListShotsApiV1VideosVideoIdShotsGet<TData = Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Shots
 */

export function useListShotsApiV1VideosVideoIdShotsGet<TData = Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShotsApiV1VideosVideoIdShotsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListShotsApiV1VideosVideoIdShotsGetQueryOptions(videoId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Get a specific shot.
 * @summary Get Shot
 */
export const getShotApiV1VideosVideoIdShotsShotIdGet = (
    videoId: string,
    shotId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ShotRead>(
      {url: `/api/v1/videos/${videoId}/shots/${shotId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetShotApiV1VideosVideoIdShotsShotIdGetQueryKey = (videoId?: string,
    shotId?: string,) => {
    return [
    `/api/v1/videos/${videoId}/shots/${shotId}`
    ] as const;
    }

    
export const getGetShotApiV1VideosVideoIdShotsShotIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError = ErrorType<HTTPValidationError>>(videoId: string,
    shotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShotApiV1VideosVideoIdShotsShotIdGetQueryKey(videoId,shotId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>> = ({ signal }) => getShotApiV1VideosVideoIdShotsShotIdGet(videoId,shotId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(videoId && shotId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetShotApiV1VideosVideoIdShotsShotIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>>
export type GetShotApiV1VideosVideoIdShotsShotIdGetQueryError = ErrorType<HTTPValidationError>


export function useGetShotApiV1VideosVideoIdShotsShotIdGet<TData = Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string,
    shotId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>,
          TError,
          Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetShotApiV1VideosVideoIdShotsShotIdGet<TData = Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string,
    shotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>,
          TError,
          Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetShotApiV1VideosVideoIdShotsShotIdGet<TData = Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string,
    shotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Shot
 */

export function useGetShotApiV1VideosVideoIdShotsShotIdGet<TData = Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError = ErrorType<HTTPValidationError>>(
 videoId: string,
    shotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShotApiV1VideosVideoIdShotsShotIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetShotApiV1VideosVideoIdShotsShotIdGetQueryOptions(videoId,shotId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Update a shot.
 * @summary Update Shot
 */
export const updateShotApiV1VideosVideoIdShotsShotIdPatch = (
    videoId: string,
    shotId: string,
    shotUpdate: BodyType<ShotUpdate>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ShotRead>(
      {url: `/api/v1/videos/${videoId}/shots/${shotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: shotUpdate
    },
      options);
    }
  


export const getUpdateShotApiV1VideosVideoIdShotsShotIdPatchMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShotApiV1VideosVideoIdShotsShotIdPatch>>, TError,{videoId: string;shotId: string;data: BodyType<ShotUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateShotApiV1VideosVideoIdShotsShotIdPatch>>, TError,{videoId: string;shotId: string;data: BodyType<ShotUpdate>}, TContext> => {

const mutationKey = ['updateShotApiV1VideosVideoIdShotsShotIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateShotApiV1VideosVideoIdShotsShotIdPatch>>, {videoId: string;shotId: string;data: BodyType<ShotUpdate>}> = (props) => {
          const {videoId,shotId,data} = props ?? {};

          return  updateShotApiV1VideosVideoIdShotsShotIdPatch(videoId,shotId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateShotApiV1VideosVideoIdShotsShotIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateShotApiV1VideosVideoIdShotsShotIdPatch>>>
    export type UpdateShotApiV1VideosVideoIdShotsShotIdPatchMutationBody = BodyType<ShotUpdate>
    export type UpdateShotApiV1VideosVideoIdShotsShotIdPatchMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Shot
 */
export const useUpdateShotApiV1VideosVideoIdShotsShotIdPatch = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShotApiV1VideosVideoIdShotsShotIdPatch>>, TError,{videoId: string;shotId: string;data: BodyType<ShotUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateShotApiV1VideosVideoIdShotsShotIdPatch>>,
        TError,
        {videoId: string;shotId: string;data: BodyType<ShotUpdate>},
        TContext
      > => {

      const mutationOptions = getUpdateShotApiV1VideosVideoIdShotsShotIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Delete a shot.
 * @summary Delete Shot
 */
export const deleteShotApiV1VideosVideoIdShotsShotIdDelete = (
    videoId: string,
    shotId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/videos/${videoId}/shots/${shotId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteShotApiV1VideosVideoIdShotsShotIdDeleteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShotApiV1VideosVideoIdShotsShotIdDelete>>, TError,{videoId: string;shotId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteShotApiV1VideosVideoIdShotsShotIdDelete>>, TError,{videoId: string;shotId: string}, TContext> => {

const mutationKey = ['deleteShotApiV1VideosVideoIdShotsShotIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteShotApiV1VideosVideoIdShotsShotIdDelete>>, {videoId: string;shotId: string}> = (props) => {
          const {videoId,shotId} = props ?? {};

          return  deleteShotApiV1VideosVideoIdShotsShotIdDelete(videoId,shotId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteShotApiV1VideosVideoIdShotsShotIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteShotApiV1VideosVideoIdShotsShotIdDelete>>>
    
    export type DeleteShotApiV1VideosVideoIdShotsShotIdDeleteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Shot
 */
export const useDeleteShotApiV1VideosVideoIdShotsShotIdDelete = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShotApiV1VideosVideoIdShotsShotIdDelete>>, TError,{videoId: string;shotId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteShotApiV1VideosVideoIdShotsShotIdDelete>>,
        TError,
        {videoId: string;shotId: string},
        TContext
      > => {

      const mutationOptions = getDeleteShotApiV1VideosVideoIdShotsShotIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Get current app settings.
 * @summary Get Settings
 */
export const getSettingsApiV1SettingsGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AppSettingsRead>(
      {url: `/api/v1/settings/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSettingsApiV1SettingsGetQueryKey = () => {
    return [
    `/api/v1/settings/`
    ] as const;
    }

    
export const getGetSettingsApiV1SettingsGetQueryOptions = <TData = Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsApiV1SettingsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>> = ({ signal }) => getSettingsApiV1SettingsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetSettingsApiV1SettingsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>>
export type GetSettingsApiV1SettingsGetQueryError = ErrorType<HTTPValidationError>


export function useGetSettingsApiV1SettingsGet<TData = Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>,
          TError,
          Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSettingsApiV1SettingsGet<TData = Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>,
          TError,
          Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSettingsApiV1SettingsGet<TData = Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Settings
 */

export function useGetSettingsApiV1SettingsGet<TData = Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsApiV1SettingsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetSettingsApiV1SettingsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Update app settings.
 * @summary Update Settings
 */
export const updateSettingsApiV1SettingsPut = (
    appSettingsUpdate: BodyType<AppSettingsUpdate>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<AppSettingsRead>(
      {url: `/api/v1/settings/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: appSettingsUpdate
    },
      options);
    }
  


export const getUpdateSettingsApiV1SettingsPutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettingsApiV1SettingsPut>>, TError,{data: BodyType<AppSettingsUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSettingsApiV1SettingsPut>>, TError,{data: BodyType<AppSettingsUpdate>}, TContext> => {

const mutationKey = ['updateSettingsApiV1SettingsPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSettingsApiV1SettingsPut>>, {data: BodyType<AppSettingsUpdate>}> = (props) => {
          const {data} = props ?? {};

          return  updateSettingsApiV1SettingsPut(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSettingsApiV1SettingsPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateSettingsApiV1SettingsPut>>>
    export type UpdateSettingsApiV1SettingsPutMutationBody = BodyType<AppSettingsUpdate>
    export type UpdateSettingsApiV1SettingsPutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Settings
 */
export const useUpdateSettingsApiV1SettingsPut = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettingsApiV1SettingsPut>>, TError,{data: BodyType<AppSettingsUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSettingsApiV1SettingsPut>>,
        TError,
        {data: BodyType<AppSettingsUpdate>},
        TContext
      > => {

      const mutationOptions = getUpdateSettingsApiV1SettingsPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
