/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Reusable cost + token count for a pipeline stage or aggregate.
 */
export interface AICost {
  token_count?: number;
  cost_usd?: number;
}
