/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { AppSettingsUpdateMasterPrompt } from './appSettingsUpdateMasterPrompt';
import type { AppSettingsUpdateRetentionDays } from './appSettingsUpdateRetentionDays';
import type { AppSettingsUpdateDefaultScriptColumn } from './appSettingsUpdateDefaultScriptColumn';
import type { AppSettingsUpdateDefaultVoiceColumn } from './appSettingsUpdateDefaultVoiceColumn';
import type { AppSettingsUpdateDefaultStyleColumn } from './appSettingsUpdateDefaultStyleColumn';
import type { AppSettingsUpdateDefaultTopTextColumn } from './appSettingsUpdateDefaultTopTextColumn';

/**
 * Schema for updating app settings.
 */
export interface AppSettingsUpdate {
  master_prompt?: AppSettingsUpdateMasterPrompt;
  retention_days?: AppSettingsUpdateRetentionDays;
  default_script_column?: AppSettingsUpdateDefaultScriptColumn;
  default_voice_column?: AppSettingsUpdateDefaultVoiceColumn;
  default_style_column?: AppSettingsUpdateDefaultStyleColumn;
  default_top_text_column?: AppSettingsUpdateDefaultTopTextColumn;
}
