/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { AppSettingsUpdateMasterPrompt } from './appSettingsUpdateMasterPrompt';
import type { AppSettingsUpdateRetentionDays } from './appSettingsUpdateRetentionDays';
import type { AppSettingsUpdateColumnDefaults } from './appSettingsUpdateColumnDefaults';

/**
 * Schema for updating app settings.
 */
export interface AppSettingsUpdate {
  master_prompt?: AppSettingsUpdateMasterPrompt;
  retention_days?: AppSettingsUpdateRetentionDays;
  column_defaults?: AppSettingsUpdateColumnDefaults;
}
