/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { AppSettingsUpdateColumnDefaultsAnyOf } from './appSettingsUpdateColumnDefaultsAnyOf';

export type AppSettingsUpdateColumnDefaults = AppSettingsUpdateColumnDefaultsAnyOf | null;
