/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for reading app settings.
 */
export interface AppSettingsRead {
  master_prompt: string;
  retention_days: number;
}
