/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ToolCall } from "./toolCall";

export type AssistantMessageToolCalls = ToolCall[] | null;
