/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AssistantMessageContent } from "./assistantMessageContent";
import type { AssistantMessageName } from "./assistantMessageName";
import type { AssistantMessageToolCalls } from "./assistantMessageToolCalls";

/**
 * An assistant message.
 */
export interface AssistantMessage {
  id: string;
  role: "assistant";
  content?: AssistantMessageContent;
  name?: AssistantMessageName;
  toolCalls?: AssistantMessageToolCalls;
}
