/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { BatchStatus } from './batchStatus';
import type { BatchReadColumnMapping } from './batchReadColumnMapping';
import type { BatchReadFileName } from './batchReadFileName';
import type { BatchReadErrorMessage } from './batchReadErrorMessage';
import type { BatchReadModelCosts } from './batchReadModelCosts';
import type { BatchReadUpdatedAt } from './batchReadUpdatedAt';

/**
 * Schema for reading a batch.
 */
export interface BatchRead {
  id: string;
  name: string;
  status: BatchStatus;
  total_videos: number;
  duration_ms?: number;
  completed_count?: number;
  failed_count?: number;
  pending_count?: number;
  column_mapping?: BatchReadColumnMapping;
  file_name?: BatchReadFileName;
  error_message?: BatchReadErrorMessage;
  model_costs?: BatchReadModelCosts;
  total_cost_usd?: number;
  created_at: string;
  updated_at?: BatchReadUpdatedAt;
}
