/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { BatchReadUpdatedAt } from './batchReadUpdatedAt';

/**
 * Schema for reading a batch with computed video stats.
 */
export interface BatchRead {
  id: string;
  name: string;
  total_videos: number;
  tokens_used?: number;
  generation_time_ms?: number;
  total_cost_usd?: number;
  avg_cost_per_video_usd?: number;
  completed?: number;
  failed?: number;
  processing?: number;
  pending?: number;
  created_at: string;
  updated_at?: BatchReadUpdatedAt;
}
