/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { BatchVideoItem } from './batchVideoItem';

/**
 * Schema for creating a batch with videos.
 */
export interface BatchCreate {
  name: string;
  videos?: BatchVideoItem[];
}
