/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Aggregate stats for a batch.
 */
export interface BatchSummary {
  batch_id: string;
  total: number;
  completed: number;
  failed: number;
  processing: number;
  pending: number;
  created_at: string;
}
