/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status of a batch in the pipeline.
 */
export type BatchStatus = typeof BatchStatus[keyof typeof BatchStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BatchStatus = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;
