/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { BatchVideoItemVoiceId } from './batchVideoItemVoiceId';
import type { BatchVideoItemStyle } from './batchVideoItemStyle';
import type { BatchVideoItemTopText } from './batchVideoItemTopText';

/**
 * Schema for a video item within a batch creation request.
 */
export interface BatchVideoItem {
  script_text: string;
  prompt?: string;
  voice_id?: BatchVideoItemVoiceId;
  style?: BatchVideoItemStyle;
  top_text?: BatchVideoItemTopText;
}
