/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

export interface BodyUploadBatchApiV1BatchesUploadPost {
  /**
   * @minLength 1
   * @maxLength 255
   */
  batch_name: string;
  column_mapping: string;
  file: string;
}
