/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */

export interface BodyUploadFileApiV1FilesUploadPost {
  thread_id: string;
  file: Blob;
}
