/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response for bulk retry — lists which videos were queued for retry.
 */
export interface BulkRetryResponse {
  retried: string[];
  skipped: string[];
}
