/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for bulk retry of failed videos.
 */
export interface BulkRetryRequest {
  /** @minItems 1 */
  video_ids: string[];
}
