/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Additional context for the agent.
 */
export interface Context {
  description: string;
  value: string;
}
