/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Stats for a single day.
 */
export interface DailyStats {
  date: string;
  videos: number;
  tokens: number;
  generation_time_ms: number;
  cost_usd: number;
}
