/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { AICost } from './aICost';

/**
 * Aggregated dashboard statistics.
 */
export interface DashboardStats {
  total_videos: number;
  completed_videos: number;
  failed_videos: number;
  processing_videos: number;
  total_batches: number;
  total_duration_ms: number;
  tts?: AICost;
  segmentation?: AICost;
  image_generation?: AICost;
  total?: AICost;
  avg_tts?: AICost;
  avg_segmentation?: AICost;
  avg_image_generation?: AICost;
  avg_total?: AICost;
  avg_duration_ms: number;
}
