/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardStats } from './dashboardStats';
import type { DailyStats } from './dailyStats';

/**
 * Full dashboard response.
 */
export interface DashboardResponse {
  stats: DashboardStats;
  daily: DailyStats[];
}
