/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Aggregated dashboard statistics.
 */
export interface DashboardStats {
  total_videos: number;
  completed_videos: number;
  failed_videos: number;
  processing_videos: number;
  total_batches: number;
  total_tokens: number;
  total_generation_time_ms: number;
  total_cost_usd: number;
  avg_tokens_per_video: number;
  avg_generation_time_ms: number;
  avg_cost_per_video_usd: number;
}
