/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardStatsModelCosts } from './dashboardStatsModelCosts';
import type { DashboardStatsAvgModelCosts } from './dashboardStatsAvgModelCosts';

/**
 * Aggregated dashboard statistics.
 */
export interface DashboardStats {
  total_videos: number;
  completed_videos: number;
  failed_videos: number;
  processing_videos: number;
  total_batches: number;
  total_duration_ms: number;
  model_costs?: DashboardStatsModelCosts;
  total_cost_usd?: number;
  avg_model_costs?: DashboardStatsAvgModelCosts;
  avg_cost_usd?: number;
  avg_duration_ms: number;
}
