/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { DeveloperMessageName } from "./developerMessageName";

/**
 * A developer message.
 */
export interface DeveloperMessage {
  id: string;
  role: "developer";
  content: string;
  name?: DeveloperMessageName;
}
