/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */

export interface FileUploadResponse {
  id: string;
  filename: string;
  file_size: number;
  mime_type: string;
  has_extracted_text: boolean;
}
