/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Name and arguments of a function call.
 */
export interface FunctionCall {
  name: string;
  arguments: string;
}
