/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { JobAnalysisProfileResponseProfileData } from './jobAnalysisProfileResponseProfileData';

/**
 * Schema for job 7D analysis profile response (read-only).
 */
export interface JobAnalysisProfileResponse {
  id: string;
  profile_data: JobAnalysisProfileResponseProfileData;
  version: number;
  created_at: string;
  updated_at: string;
  job_id: string;
}
