/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { JobWithOrganizationRequirements } from './jobWithOrganizationRequirements';
import type { JobWithOrganizationLocation } from './jobWithOrganizationLocation';
import type { JobWithOrganizationJobUrl } from './jobWithOrganizationJobUrl';
import type { JobWithOrganizationEmploymentType } from './jobWithOrganizationEmploymentType';
import type { JobWithOrganizationSeniority } from './jobWithOrganizationSeniority';
import type { JobWithOrganizationSalaryMin } from './jobWithOrganizationSalaryMin';
import type { JobWithOrganizationSalaryMax } from './jobWithOrganizationSalaryMax';
import type { JobWithOrganizationSalaryCurrency } from './jobWithOrganizationSalaryCurrency';
import type { JobWithOrganizationIsRemote } from './jobWithOrganizationIsRemote';
import type { JobWithOrganizationDatePosted } from './jobWithOrganizationDatePosted';
import type { OrganizationBase } from './organizationBase';
import type { JobWithOrganizationJob7dProfile } from './jobWithOrganizationJob7dProfile';
import type { JobWithOrganizationMatchScore } from './jobWithOrganizationMatchScore';
import type { JobWithOrganizationMatchPercentage } from './jobWithOrganizationMatchPercentage';

/**
 * Schema for job with nested organization data.
 */
export interface JobWithOrganization {
  id: string;
  created_at: string;
  updated_at: string;
  title: string;
  description: string;
  requirements?: JobWithOrganizationRequirements;
  location?: JobWithOrganizationLocation;
  job_url?: JobWithOrganizationJobUrl;
  employment_type?: JobWithOrganizationEmploymentType;
  seniority?: JobWithOrganizationSeniority;
  salary_min?: JobWithOrganizationSalaryMin;
  salary_max?: JobWithOrganizationSalaryMax;
  salary_currency?: JobWithOrganizationSalaryCurrency;
  is_remote?: JobWithOrganizationIsRemote;
  date_posted?: JobWithOrganizationDatePosted;
  organization_id: string;
  user_id: string;
  is_active?: boolean;
  organization: OrganizationBase;
  job_7d_profile?: JobWithOrganizationJob7dProfile;
  match_score?: JobWithOrganizationMatchScore;
  match_percentage?: JobWithOrganizationMatchPercentage;
}
