/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { JobAnalysisProfileResponse } from './jobAnalysisProfileResponse';

export type JobWithOrganizationJob7dProfile = JobAnalysisProfileResponse | null;
