/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Camera movement direction for the Ken Burns pan/zoom effect.
 */
export type KenBurnsDirection = typeof KenBurnsDirection[keyof typeof KenBurnsDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KenBurnsDirection = {
  zoom_in: 'zoom_in',
  zoom_out: 'zoom_out',
  pan_left: 'pan_left',
  pan_right: 'pan_right',
  pan_up: 'pan_up',
  pan_down: 'pan_down',
} as const;
