/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { KenBurnsDirection } from './kenBurnsDirection';

/**
 * Ken Burns pan/zoom camera movement applied to a still image.
 */
export interface KenBurnsEffect {
  type?: 'ken_burns';
  direction: KenBurnsDirection;
  /** Zoom scale factor, ideally between 1.1 and 1.4 */
  scale: number;
}
