/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */

export type Locale = (typeof Locale)[keyof typeof Locale];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Locale = {
  en: "en",
  lt: "lt",
  ru: "ru",
} as const;
