/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationBaseDescription } from './organizationBaseDescription';
import type { OrganizationBaseWebsite } from './organizationBaseWebsite';
import type { OrganizationBaseLogoUrl } from './organizationBaseLogoUrl';
import type { OrganizationBaseIndustry } from './organizationBaseIndustry';
import type { OrganizationBaseSize } from './organizationBaseSize';
import type { OrganizationBaseHeadquarters } from './organizationBaseHeadquarters';
import type { OrganizationBaseFoundedYear } from './organizationBaseFoundedYear';
import type { OrganizationBaseSpecialties } from './organizationBaseSpecialties';
import type { OrganizationBaseLinkedinUrl } from './organizationBaseLinkedinUrl';

/**
 * Base organization schema with all fields.
 */
export interface OrganizationBase {
  id: string;
  created_at: string;
  updated_at: string;
  name: string;
  description?: OrganizationBaseDescription;
  website?: OrganizationBaseWebsite;
  logo_url?: OrganizationBaseLogoUrl;
  industry?: OrganizationBaseIndustry;
  size?: OrganizationBaseSize;
  headquarters?: OrganizationBaseHeadquarters;
  founded_year?: OrganizationBaseFoundedYear;
  specialties?: OrganizationBaseSpecialties;
  linkedin_url?: OrganizationBaseLinkedinUrl;
  user_id: string;
}
