/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { BatchRead } from './batchRead';

export interface PageResponseBatchRead {
  items: BatchRead[];
  page: number;
  page_size: number;
  total: number;
  total_pages: number;
}
