/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Context } from "./context";
import type { RunAgentInputMessagesItem } from "./runAgentInputMessagesItem";
import type { Tool } from "./tool";

/**
 * Input for running an agent.
 */
export interface RunAgentInput {
  threadId: string;
  runId: string;
  state: unknown;
  messages: RunAgentInputMessagesItem[];
  tools: Tool[];
  context: Context[];
  forwardedProps: unknown;
}
