/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AssistantMessage } from "./assistantMessage";
import type { DeveloperMessage } from "./developerMessage";
import type { SystemMessage } from "./systemMessage";
import type { ToolMessage } from "./toolMessage";
import type { UserMessage } from "./userMessage";

export type RunAgentInputMessagesItem =
  | DeveloperMessage
  | SystemMessage
  | AssistantMessage
  | UserMessage
  | ToolMessage;
