/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status of a shot in the image generation pipeline.
 */
export type ShotStatus = typeof ShotStatus[keyof typeof ShotStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShotStatus = {
  pending: 'pending',
  generating: 'generating',
  generated: 'generated',
  failed: 'failed',
} as const;
