/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { ShotReadKenBurnsConfig } from './shotReadKenBurnsConfig';
import type { ShotReadImageUrl } from './shotReadImageUrl';
import type { ShotReadUpdatedAt } from './shotReadUpdatedAt';

/**
 * Schema for reading a shot.
 */
export interface ShotRead {
  order: number;
  text: string;
  image_prompt: string;
  ken_burns_config?: ShotReadKenBurnsConfig;
  start_time: number;
  end_time: number;
  id: string;
  video_id: string;
  image_url?: ShotReadImageUrl;
  tokens_used?: number;
  generation_time_ms?: number;
  cost_usd?: number;
  created_at: string;
  updated_at?: ShotReadUpdatedAt;
}
