/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { ShotCreateKenBurnsConfig } from './shotCreateKenBurnsConfig';

/**
 * Schema for creating a shot.
 */
export interface ShotCreate {
  order: number;
  text: string;
  image_prompt: string;
  ken_burns_config?: ShotCreateKenBurnsConfig;
  start_time: number;
  end_time: number;
  video_id: string;
}
