/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { KenBurnsEffect } from './kenBurnsEffect';

export type ShotCreateEffectConfig = KenBurnsEffect | null;
