/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { ShotUpdateOrder } from './shotUpdateOrder';
import type { ShotUpdateText } from './shotUpdateText';
import type { ShotUpdateImagePrompt } from './shotUpdateImagePrompt';
import type { ShotUpdateKenBurnsConfig } from './shotUpdateKenBurnsConfig';
import type { ShotUpdateStartTime } from './shotUpdateStartTime';
import type { ShotUpdateEndTime } from './shotUpdateEndTime';
import type { ShotUpdateImageUrl } from './shotUpdateImageUrl';

/**
 * Schema for updating a shot (all fields optional).
 */
export interface ShotUpdate {
  order?: ShotUpdateOrder;
  text?: ShotUpdateText;
  image_prompt?: ShotUpdateImagePrompt;
  ken_burns_config?: ShotUpdateKenBurnsConfig;
  start_time?: ShotUpdateStartTime;
  end_time?: ShotUpdateEndTime;
  image_url?: ShotUpdateImageUrl;
}
