/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { SystemMessageName } from "./systemMessageName";

/**
 * A system message.
 */
export interface SystemMessage {
  id: string;
  role: "system";
  content: string;
  name?: SystemMessageName;
}
