/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { FunctionCall } from "./functionCall";

/**
 * A tool call, modelled after OpenAI tool calls.
 */
export interface ToolCall {
  id: string;
  type: "function";
  function: FunctionCall;
}
