/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * A tool result message.
 */
export interface ToolMessage {
  id: string;
  role: "tool";
  content: string;
  toolCallId: string;
}
