/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * A tool definition.
 */
export interface Tool {
  name: string;
  description: string;
  parameters: unknown;
}
