/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { UserMessageName } from "./userMessageName";

/**
 * A user message.
 */
export interface UserMessage {
  id: string;
  role: "user";
  content: string;
  name?: UserMessageName;
}
