/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { VideoCreateStyle } from './videoCreateStyle';
import type { VideoCreateTopText } from './videoCreateTopText';
import type { VideoCreatePrompt } from './videoCreatePrompt';
import type { VideoCreateBatchId } from './videoCreateBatchId';

/**
 * Schema for creating a video (also used as pipeline input).
 */
export interface VideoCreate {
  /**
   * Ad script text to convert to video
   * @minLength 1
   */
  script_text: string;
  /**
   * TTS voice identifier
   * @minLength 1
   * @maxLength 255
   */
  voice_id: string;
  style?: VideoCreateStyle;
  top_text?: VideoCreateTopText;
  prompt?: VideoCreatePrompt;
  batch_id?: VideoCreateBatchId;
}
