/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { VideoUpdateScriptText } from './videoUpdateScriptText';
import type { VideoUpdatePrompt } from './videoUpdatePrompt';
import type { VideoUpdateVoiceId } from './videoUpdateVoiceId';
import type { VideoUpdateStyle } from './videoUpdateStyle';
import type { VideoUpdateTopText } from './videoUpdateTopText';
import type { VideoUpdateStatus } from './videoUpdateStatus';
import type { VideoUpdateCurrentStage } from './videoUpdateCurrentStage';
import type { VideoUpdateErrorMessage } from './videoUpdateErrorMessage';
import type { VideoUpdateOutputUrl } from './videoUpdateOutputUrl';

/**
 * Schema for updating a video (all fields optional).
 */
export interface VideoUpdate {
  script_text?: VideoUpdateScriptText;
  prompt?: VideoUpdatePrompt;
  voice_id?: VideoUpdateVoiceId;
  style?: VideoUpdateStyle;
  top_text?: VideoUpdateTopText;
  status?: VideoUpdateStatus;
  current_stage?: VideoUpdateCurrentStage;
  error_message?: VideoUpdateErrorMessage;
  output_url?: VideoUpdateOutputUrl;
}
