/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { VideoStatus } from './videoStatus';

export type VideoUpdateStatus = VideoStatus | null;
