/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { VideoReadWithShotsBatchId } from './videoReadWithShotsBatchId';
import type { VideoReadWithShotsStyle } from './videoReadWithShotsStyle';
import type { VideoReadWithShotsTopText } from './videoReadWithShotsTopText';
import type { VideoReadWithShotsPrompt } from './videoReadWithShotsPrompt';
import type { VideoStatus } from './videoStatus';
import type { VideoStage } from './videoStage';
import type { VideoReadWithShotsErrorMessage } from './videoReadWithShotsErrorMessage';
import type { VideoReadWithShotsOutputUrl } from './videoReadWithShotsOutputUrl';
import type { VideoReadWithShotsModelCosts } from './videoReadWithShotsModelCosts';
import type { VideoReadWithShotsUpdatedAt } from './videoReadWithShotsUpdatedAt';
import type { ShotRead } from './shotRead';

/**
 * Schema for reading a video with its shots.
 */
export interface VideoReadWithShots {
  id: string;
  batch_id?: VideoReadWithShotsBatchId;
  script_text: string;
  voice_id: string;
  style?: VideoReadWithShotsStyle;
  top_text?: VideoReadWithShotsTopText;
  prompt?: VideoReadWithShotsPrompt;
  status: VideoStatus;
  current_stage: VideoStage;
  error_message?: VideoReadWithShotsErrorMessage;
  output_url?: VideoReadWithShotsOutputUrl;
  duration_ms?: number;
  file_size_bytes?: number;
  model_costs?: VideoReadWithShotsModelCosts;
  total_cost_usd?: number;
  created_at: string;
  updated_at?: VideoReadWithShotsUpdatedAt;
  shots?: ShotRead[];
}
