/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Current pipeline stage for a video.
 */
export type VideoStage = typeof VideoStage[keyof typeof VideoStage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VideoStage = {
  queued: 'queued',
  tts: 'tts',
  segmentation: 'segmentation',
  image_generation: 'image_generation',
  assembly: 'assembly',
  upload: 'upload',
  done: 'done',
} as const;
