/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { VideoReadWithShotsVoiceId } from './videoReadWithShotsVoiceId';
import type { VideoReadWithShotsStyle } from './videoReadWithShotsStyle';
import type { VideoReadWithShotsBatchId } from './videoReadWithShotsBatchId';
import type { VideoReadWithShotsErrorMessage } from './videoReadWithShotsErrorMessage';
import type { VideoReadWithShotsOutputUrl } from './videoReadWithShotsOutputUrl';
import type { VideoReadWithShotsUpdatedAt } from './videoReadWithShotsUpdatedAt';
import type { ShotRead } from './shotRead';

/**
 * Schema for reading a video with its shots.
 */
export interface VideoReadWithShots {
  script_text: string;
  voice_id?: VideoReadWithShotsVoiceId;
  style?: VideoReadWithShotsStyle;
  id: string;
  batch_id?: VideoReadWithShotsBatchId;
  status: string;
  current_stage: string;
  error_message?: VideoReadWithShotsErrorMessage;
  output_url?: VideoReadWithShotsOutputUrl;
  created_at: string;
  updated_at?: VideoReadWithShotsUpdatedAt;
  shots?: ShotRead[];
}
