/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { VideoReadVoiceId } from './videoReadVoiceId';
import type { VideoReadStyle } from './videoReadStyle';
import type { VideoReadBatchId } from './videoReadBatchId';
import type { VideoReadErrorMessage } from './videoReadErrorMessage';
import type { VideoReadOutputUrl } from './videoReadOutputUrl';
import type { VideoReadUpdatedAt } from './videoReadUpdatedAt';

/**
 * Schema for reading a video.
 */
export interface VideoRead {
  script_text: string;
  voice_id?: VideoReadVoiceId;
  style?: VideoReadStyle;
  id: string;
  batch_id?: VideoReadBatchId;
  status: string;
  current_stage: string;
  error_message?: VideoReadErrorMessage;
  output_url?: VideoReadOutputUrl;
  created_at: string;
  updated_at?: VideoReadUpdatedAt;
}
