/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { VideoCreateVoiceId } from './videoCreateVoiceId';
import type { VideoCreateStyle } from './videoCreateStyle';
import type { VideoCreateBatchId } from './videoCreateBatchId';

/**
 * Schema for creating a video.
 */
export interface VideoCreate {
  script_text: string;
  voice_id?: VideoCreateVoiceId;
  style?: VideoCreateStyle;
  batch_id?: VideoCreateBatchId;
}
