/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status of a video in the pipeline.
 */
export type VideoStatus = typeof VideoStatus[keyof typeof VideoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VideoStatus = {
  processing: 'processing',
  finished: 'finished',
  failed: 'failed',
} as const;
