/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 0.1.0
 */
import type { VideoReadBatchId } from './videoReadBatchId';
import type { VideoReadStyle } from './videoReadStyle';
import type { VideoReadTopText } from './videoReadTopText';
import type { VideoReadPrompt } from './videoReadPrompt';
import type { VideoStatus } from './videoStatus';
import type { VideoStage } from './videoStage';
import type { VideoReadErrorMessage } from './videoReadErrorMessage';
import type { VideoReadOutputUrl } from './videoReadOutputUrl';
import type { AICost } from './aICost';
import type { VideoReadUpdatedAt } from './videoReadUpdatedAt';

/**
 * Schema for reading a video.
 */
export interface VideoRead {
  id: string;
  batch_id?: VideoReadBatchId;
  script_text: string;
  voice_id: string;
  style?: VideoReadStyle;
  top_text?: VideoReadTopText;
  prompt?: VideoReadPrompt;
  status: VideoStatus;
  current_stage: VideoStage;
  error_message?: VideoReadErrorMessage;
  output_url?: VideoReadOutputUrl;
  duration_ms?: number;
  file_size_bytes?: number;
  tts?: AICost;
  segmentation?: AICost;
  image_generation?: AICost;
  total?: AICost;
  created_at: string;
  updated_at?: VideoReadUpdatedAt;
}
